# Generated by Django 5.1.2 on 2024-11-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi_app.kpi'),
        ),
    ]
